blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/GitH22Ash/Allotment_Tracker#readme
    about: Please check the docs before creating an issue.
  - name: 💬 Discussions
    url: https://github.com/GitH22Ash/Allotment_Tracker/discussions
    about: For general questions or ideas, use discussions instead of issues.
